name: twimzi
description: Digital Operating System for Every Local Business.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # -------------------------
  # State Management
  # -------------------------
  flutter_riverpod: ^2.6.1

  # -------------------------
  # Navigation
  # -------------------------
  go_router: ^16.2.0

  # -------------------------
  # Backend
  # -------------------------
  supabase_flutter: ^2.10.0
  google_sign_in: ^7.1.1

  # -------------------------
  # Networking
  # -------------------------
  dio: ^5.9.0
  internet_connection_checker_plus: ^2.7.2

  # -------------------------
  # Local Storage
  # -------------------------
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

  # -------------------------
  # UI
  # -------------------------
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0

  # -------------------------
  # Forms & Validation
  # -------------------------
  form_validator: ^2.1.1

  # -------------------------
  # Utilities
  # -------------------------
  intl: ^0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.7
  logger: ^2.6.1
  collection: ^1.19.1

  # -------------------------
  # Image Handling
  # -------------------------
  image_picker: ^1.2.0
  image: ^4.5.4
  path: ^1.9.1
  path_provider: ^2.1.5
  mime: ^2.0.0

  # -------------------------
  # Device
  # -------------------------
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/animations/
    - assets/fonts/